{
 "title": "go test fromo json",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "client", "label": "Client", "query": "label_values(client)" }
  ]
 },
 "panels": [
  {
   "title": "Response average",
   "type": "singlestat",
   "description": "Overall average response time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(client_balance_response_duration_histogram_sum{operation=\"balance_update\"}[30m])\n/\nrate(client_balance_response_duration_histogram_count{operation=\"balance_update\"}[30m])"
    }
   ]
  },
  {
   "title": "Response duration",
   "type": "heatmap",
   "description": "Balance response duration (ms)",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(client_balance_response_duration_histogram_bucket[30m])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "Response code",
   "type": "graph",
   "description": "Number of HTTP responses - last 30 minutes",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(increase(client_http_response_counter{operation=\"balance_update\"}[30m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP 2XX total",
   "type": "singlestat",
   "description": "Number of HTTP 2XX responses - until now",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(client_http_response_counter{operation=\"balance_update\",code=~\"2.*\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 4XX total",
   "type": "singlestat",
   "description": "Number of HTTP 4XX responses - until now",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(client_http_response_counter{operation=\"balance_update\",code=~\"4.*\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 5XX total",
   "type": "singlestat",
   "description": "Number of HTTP 5XX responses - until now",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(client_http_response_counter{operation=\"balance_update\",code=~\"5.*\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Current",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "format": "currencyGBP",
   "valueName": "current",
   "targets": [
    { "expr": "client_balance_gauge" }
   ]
  },
  {
   "title": "History",
   "type": "graph",
   "description": "Changes in balance",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "client_balance_gauge", "legendFormat": "balance" }
   ]
  },
  {
   "title": "Activity - $client",
   "type": "graph",
   "description": "Balance activity history - until now",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(client_balance_activity_counter{client=~\"$client\"}) by (activity)",
     "legendFormat": "{{activity}}"
    }
   ]
  }
 ]
}